# Generated by Django 3.0.3 on 2020-02-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('modified', models.DateTimeField()),
                ('featured', models.BooleanField()),
                ('uuid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.URLField(blank=True, null=True)),
                ('self', models.URLField(blank=True, null=True)),
                ('presentation', models.URLField(blank=True, null=True)),
                ('content_sequence', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('text', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Links')),
                ('tag_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Tag_type')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.IntegerField()),
                ('asset_class', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('primary', models.BooleanField()),
                ('seo_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('syndicate', models.BooleanField()),
                ('valid', models.BooleanField()),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('path', models.URLField()),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fool_uid', models.IntegerField()),
                ('primary', models.BooleanField()),
                ('twitter_username', models.CharField(blank=True, max_length=50, null=True)),
                ('small_avatar_url', models.URLField()),
                ('long_bio', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('byline', models.CharField(max_length=50)),
                ('uuid', models.CharField(max_length=50)),
                ('contributor_type', models.CharField(max_length=50)),
                ('large_avatar_url', models.URLField()),
                ('short_bio', models.CharField(max_length=250)),
                ('author_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure', models.CharField(max_length=250)),
                ('promo', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('visibility', models.IntegerField()),
                ('article_type', models.CharField(max_length=50)),
                ('publish_at', models.DateTimeField()),
                ('path', models.URLField()),
                ('static_page', models.BooleanField()),
                ('author_override', models.BooleanField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('headline', models.CharField(max_length=50)),
                ('modified', models.DateTimeField()),
                ('product_id', models.IntegerField()),
                ('video', models.URLField(blank=True, null=True)),
                ('byline', models.CharField(max_length=50)),
                ('authors', models.ManyToManyField(to='content_api.Author')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Bureau')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Collection')),
                ('images', models.ManyToManyField(to='content_api.Image')),
                ('instruments', models.ManyToManyField(to='content_api.Instrument')),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Links')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_api.Pitch')),
                ('tags', models.ManyToManyField(to='content_api.Tag')),
            ],
        ),
    ]
