# Generated by Django 3.0.3 on 2020-02-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_api.Bureau'),
        ),
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
