# Generated by Django 3.0.3 on 2020-02-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0002_auto_20200217_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_api.Collection'),
        ),
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_api.Links'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pitch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_api.Pitch'),
        ),
    ]
